# /*----------------------------------------------------------------------------8
# |                                                                            |
# |                         PLAYBOOK FOR BOM DOWNLOADER                        |
# |                                                                            |
# +------------------------------------4--------------------------------------*/
---

# Steps:
#   01) Process BOM (Validate and Extract)
#

- hosts:          localhost

  name:           BOM Downloader
  gather_facts:   false
  connection:     local
  become:         no
  become_user:    root
 
  vars_files:
    - vars/ansible-input-api.yaml                               # API Input template with defaults


  tasks:
# -------------------------------------+---------------------------------------8
#
# Build the list of tasks to be executed in order here. 
#
# -------------------------------------+---------------------------------------8

  - block:
    - include_role:
        name:     roles-misc/0.3.sap-installation-media-storage-details
        public:   yes      
    tags:
      - 0.3.sap-installation-media-storage-details


  - ansible.builtin.set_fact:
      tier:     "uploader"

  - block:
    - include_role:
        name:     roles-sap/0.1-bom-validator
    vars:
      sapbits_location_base_path: "{{ hostvars.localhost.sapbits-location-base-path }}"
      sapbits_sas_token:          "{{ hostvars.localhost.sapbits_sas_token }}"
    tags:
      - 0.1-bom-validator


...
# /*---------------------------------------------------------------------------8
# |                                   END                                      |
# +------------------------------------4--------------------------------------*/
