# /*----------------------------------------------------------------------------8
# |                                                                             |
# | Playbook for PACEMAKER General Config                                       |
# | This playbook will setup a generic pacemaker cluster on DB and SCS hosts    | 
# | The playbook user Azure fence Agent for node fencing. It gets the SPN       |  
# | credentions from Key Vault. These credentianls are used to create Stonith.  |                                                              |
# +------------------------------------4---------------------------------------*| 
---

# TODO: 
#  

- hosts: localhost
  name: Get SPN from KeyVault
  remote_user:    "{{ orchestration_ansible_user }}"
  become:         no
  become_user:    root
  gather_facts:   yes
  vars_files:
    - vars/ansible-input-api.yaml                               # API Input template with defaults
  tasks:
  - ansible.builtin.set_fact:
      tier:  fencing

  - include_role:
      name:     roles-misc/0.2-kv-secrets
      public:   yes      
    tags:
       - kv-secrets

  - include_role:
      name:     roles-misc/0.1-passwords
      public:   yes      
    tags:
       - 0.1-passwords


- hosts:          "{{ sap_sid|upper }}_DB"  

  name:           PACEMAKER - General Config - Database
  remote_user:    "{{ orchestration_ansible_user }}"                
  become:         yes
  become_user:    root
  gather_facts:   true
  vars_files:
    - vars/ansible-input-api.yaml                               # API Input template with defaults


# -------------------------------------+---------------------------------------8
#
# Build the list of tasks to be executed in order here. 
#
# -------------------------------------+---------------------------------------8

# Specify the active tier for this playbook run

  tasks:
  - ansible.builtin.set_fact:
      tier:     ha
      hana_password_master:       "{{ hostvars.localhost.sap_password }}"
      password_ha_db_cluster:     "{{ hostvars.localhost.db_cluster_password }}"
    tags:
      - always

  - name: "Setting the pacemaker facts -DB"
    ansible.builtin.set_fact:
      primary_instance_name:                     "{{ ansible_play_hosts_all[0] }}"         # Setting up Primary Instance Name
      secondary_instance_name:                   "{{ ansible_play_hosts_all[1] }}"         # Setting up Secondary Instance Name
      sap_hana_fencing_spn_client_id:            "{{ hostvars.localhost.sap_fencing_spn_client_id }}"
      sap_hana_fencing_spn_client_pwd:           "{{ hostvars.localhost.sap_fencing_spn_pwd }}"
      sap_hana_fencing_spn_tenant_id:            "{{ hostvars.localhost.sap_fencing_spn_tenant_id }}"

  - block:
      - include_role:
          name:     roles-os/1.3-repository                             # Repo required for JQ package 
    tags:
       - 1.3-repository
 
  - block:
      - include_role:
          name:     roles-os/1.4-packages                               # Install the HA packages required for pacemaker
    tags:
      - 1.4-packages
       
  - block:
      - include_role:
          name:     roles-os/1.9-kernelparameters                       # Setup the kernel parameters required for pacemaker cluster VMs
    tags:
      - 1.9-kernelparameters

  - block:
    - include_role:
          name:     roles-os/1.16-services
    tags:
      - 1.16-services

  - block:
    - include_role:
          name:     roles-os/1.11-accounts
    tags:
      - 1.11-accounts

  - block:
      - include_role:
          name:     roles-os/1.17-generic-pacemaker                         # Configures the Pacemaker cluster with Azure fence agent 
        when: db_high_availability == true          
    tags:
      - 1.17-generic-pacemaker

- hosts:          "{{ sap_sid|upper }}_SCS  :
                  {{ sap_sid|upper }}_ERS"  

  name:           PACEMAKER - General - Config - Central Services
  remote_user:    "{{ orchestration_ansible_user }}"                
  become:         yes
  become_user:    root
  gather_facts:   true
  vars_files:
    - vars/ansible-input-api.yaml                               # API Input template with defaults

# -------------------------------------+---------------------------------------8
#
# Build the list of tasks to be executed in order here. 
#
# -------------------------------------+---------------------------------------8

# Specify the active tier for this playbook run

  tasks:
  - ansible.builtin.set_fact:
      tier:     ha
    tags:
      - always

  - name: "Setting the pacemaker facts - SCS"
    ansible.builtin.set_fact:
      primary_instance_name:                     "{{ ansible_play_hosts_all[0] }}"         # Setting up Primary Instance Name
      secondary_instance_name:                   "{{ ansible_play_hosts_all[1] }}"         # Setting up Secondary Instance Name
      sap_hana_fencing_spn_client_id:            "{{ hostvars.localhost.sap_fencing_spn_client_id }}"
      sap_hana_fencing_spn_client_pwd:           "{{ hostvars.localhost.sap_fencing_spn_pwd }}"
      sap_hana_fencing_spn_tenant_id:            "{{ hostvars.localhost.sap_fencing_spn_tenant_id }}"
    when: scs_high_availability == true

  - block:
      - include_role:
          name:     roles-os/1.3-repository                             # Repo required for JQ package 
        when: scs_high_availability == true
    tags:
       - 1.3-repository
    
 
  - block:
      - include_role:
          name:     roles-os/1.4-packages                               # Install the HA packages required for pacemaker
        when: scs_high_availability == true
    tags:
      - 1.4-packages
    
       
  - block:
      - include_role:
          name:     roles-os/1.9-kernelparameters                       # Setup the kernel parameters required for pacemaker cluster VMs
        when: scs_high_availability == true
    tags:
      - 1.9-kernelparameters

  - block:
    - include_role:
        name:     roles-os/1.16-services
      when: scs_high_availability == true
    tags:
      - 1.16-services
    

  - block:
      - include_role:
          name:     roles-os/1.17-generic-pacemaker                         # Configures the Pacemaker cluster with Azure fence agent 
        when: scs_high_availability == true                       # Needs more logic
    tags:
      - 1.17-generic-pacemaker

- hosts: localhost
  name: Log results
  remote_user:    "{{ orchestration_ansible_user }}"
  become:         no
  become_user:    root
  gather_facts:   yes
  vars_files:
    - vars/ansible-input-api.yaml                               # API Input template with defaults
  tasks:
  - ansible.builtin.file:
      path: "{{ _workspace_directory }}/.step6"
      state: touch
    when: scs_high_availability == true



...
# /*----------------------------------------------------------------------------8
# |                                    END                                      |
# +------------------------------------4--------------------------------------*/
