# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                       Playbook for SAP SCS Install                         |
# |                                                                            |
# +------------------------------------4--------------------------------------*/
---

- hosts: localhost
  name: Get SAP Password from KeyVault
  remote_user:    "{{ orchestration_ansible_user }}"
  become:         no
  become_user:    root
  gather_facts:   yes
  vars_files:
    - vars/ansible-input-api.yaml                               # API Input template with defaults
  tasks:

  - include_role:
      name:     roles-misc/0.1-passwords
      public:   yes      
    tags:
       - 0.1-passwords


  - ansible.builtin.file:
      path: "{{ _workspace_directory }}/.step5"
      state: absent

#      


- hosts:          "{{ sap_sid|upper }}_SCS :
                  {{ sap_sid|upper }}_ERS"

  name:           SAP Installation - SCS
  remote_user:    "{{ orchestration_ansible_user }}"                
  become:         yes
  become_user:    root
  gather_facts:   true
  vars_files:
    - vars/ansible-input-api.yaml                                               # API Input template with defaults


  tasks:
# -------------------------------------+---------------------------------------8
#
# Build the list of tasks to be executed in order here. 
#
# -------------------------------------+---------------------------------------8

  - ansible.builtin.set_fact:
      tier:     scs
      hana_password_master:    "{{ hostvars.localhost.sap_password }}"
    tags:
      - always

# - role: sap-users                                             # --> roles-sap/sap-users (playbook_02_os_sap_specific_config)
  - block:
    - include_role:
        name:     roles-sap-os/2.5-sap-users                          # TODO: Centiq copy (rework done)
    tags:
      - 2.5-sap-users

  - block:
      - include_role:
          name:     roles-sap-os/2.6-sap-mounts
    tags:
      - 2.6-sap-mounts

  - block:
      - include_role:
          name:     roles-sap/5.0.0-scs-install
    tags:
      - 5.0.0-scs-install

- hosts: localhost
  name: Log results
  remote_user:    "{{ orchestration_ansible_user }}"
  become:         no
  become_user:    root
  gather_facts:   yes
  vars_files:
    - vars/ansible-input-api.yaml                               # API Input template with defaults
  tasks:
  - ansible.builtin.file:
      path: "{{ _workspace_directory }}/.step5"
      state: touch


...
# /*---------------------------------------------------------------------------8
# |                                    END                                     |
# +------------------------------------4--------------------------------------*/
