# /*---------------------------------------------------------------------------8
# |                                                                            |
# |                 Playbook for SAP Web Dispatcher Install                    |
# |                                                                            |
# +------------------------------------4--------------------------------------*/
---

- hosts:          "{{ sap_sid|upper }}_WEB"

  name:           SAP Installation - WebDispatcher
  remote_user:    "{{ orchestration_ansible_user }}"
  serial:         1                                                             # /usr/sap/install is an NFS and we share SID/instance number - must be ran serially    
  become:         yes
  become_user:    root
  gather_facts:   true
  vars_files:
    - vars/ansible-input-api.yaml                                               # API Input template with defaults


  tasks:
# -------------------------------------+---------------------------------------8
#
# Build the list of tasks to be executed in order here. 
#
# -------------------------------------+---------------------------------------8
  - set_fact:
      tier:     web                                                             # SAP Install phase: Web Dispatcher

  - include_role:
      name:     roles-sap-os/2.6-sap-mounts

  - include_role:
      name:     roles-sap/5.4-web-install

...
# /*---------------------------------------------------------------------------8
# |                                    END                                     |
# +------------------------------------4--------------------------------------*/
