# /*----------------------------------------------------------------------------8
# |                                                                            |
# |                      Playbook for PACEMAKER General Config                 |
# | This playbook will setup a generic pacemaker cluster on DB and SCS hosts   | 
# |                                                                            |
# +------------------------------------4--------------------------------------*/
---

# TODO: Playbook not yet written
#       This is a placeholder 

- hosts:          "{{ sap_sid|upper }}_DB  :
                   {{ sap_sid|upper }}_SCS"                                           

  name:           PACEMAKER - General Config
  remote_user:    "{{ orchestration_ansible_user }}"                
  become:         yes
  become_user:    root
  gather_facts:   true
  vars_files:
    - vars/ansible-input-api.yaml                               # API Input template with defaults


  tasks:

  # - name: Test Connection                                     # Simple connection test for troubleshooting
  #   ping:


  tasks:
# -------------------------------------+---------------------------------------8
#
# Build the list of tasks to be executed in order here. 
#
# -------------------------------------+---------------------------------------8

  # Specify the active tier for this playbook run
 # - set_fact:
 #     tier:     os

  - include_role:
      name:     roles-os/6.0.0.0-Generic

#----------------------------------------
# BEGIN
#
# TODO: evaluate for inclusion and refactor.
# SOURCE: sap-playbook
#----------------------------------------

# # Only SLES support SBD fencing
# - hosts: iscsi
#   become: true
#   become_user: root
#   roles:
#    - role: iscsi-target-install
#      when:
#        - hana_database.size != "LargeInstance"
#        - hana_database.high_availability
#        - hostvars[hana_database.nodes[0].ip_admin_nic].ansible_os_family == 'Suse'

#----------------------------------------
# END
#----------------------------------------


...
# /*----------------------------------------------------------------------------8
# |                                    END                                      |
# +------------------------------------4--------------------------------------*/
