# /*----------------------------------------------------------------------------8
# |                                                                            |
# |                         PLAYBOOK FOR BOM PROCESSING                         |
# |                                                                            |
# +------------------------------------4--------------------------------------*/
---

# Steps:
#   01) NFS: Make Local Shares available via NFS Exports
#   02) Process BOM (Download and Extract)
#

- hosts:          "{{ sap_sid|upper }}_SCS"

  name:           BOM Processing
  remote_user:    "{{ orchestration_ansible_user }}"                
  become:         yes
  become_user:    root
  gather_facts:   true
  vars_files:
    - vars/ansible-input-api.yaml                               # API Input template with defaults


  tasks:
# -------------------------------------+---------------------------------------8
#
# Build the list of tasks to be executed in order here. 
#
# -------------------------------------+---------------------------------------8

  - set_fact:
      tier:     preparation
    tags:
      - always
# Uses the same role as the OS plabook but is controlled by the sapos tier setting
  - block:
    - include_role:
        name:     roles-os/1.5-disk-setup
    tags:
      - 1.5-disk-setup 

  - block:
    - include_role:
        name:     roles-sap-os/2.3-sap-exports
    tags:
      - 2.3-sap-exports

  - block:
      - include_role:
          name:     roles-os/1.16-services
    tags:
      - 1.16-services

  - block:
    - include_role:
        name:     roles-sap-os/2.6-sap-mounts
    tags:
      - 2.6-sap-mounts

  - block:
    - include_role:
        name:     roles-sap/3.3-bom-processing
    tags:
      - 3.3-bom-processing


...
# /*---------------------------------------------------------------------------8
# |                                   END                                      |
# +------------------------------------4--------------------------------------*/
