# /*----------------------------------------------------------------------------8
# |                                                                            |
# |         Playbook for performing SAP specific OS configuration tasks         |
# |                                                                            |
# +------------------------------------4--------------------------------------*/
---

- hosts:          "{{ sap_sid|upper }}_DB  :
                   {{ sap_sid|upper }}_SCS :
                   {{ sap_sid|upper }}_PAS :
                   {{ sap_sid|upper }}_APP :
                   {{ sap_sid|upper }}_WEB"

  name:           OS - SAP specific configuration
  remote_user:    "{{ orchestration_ansible_user }}"                
  become:         yes
  become_user:    root
  gather_facts:   true
  vars_files:
    - vars/ansible-input-api.yaml                               # API Input template with defaults


  tasks:
# -------------------------------------+---------------------------------------8
#
# Build the list of tasks to be executed in order here. 
#
# -------------------------------------+---------------------------------------8
  - set_fact:
      tier:     sapos
    tags:
      - always

  - include_role:
      name:     roles-sap-os/2.4-hosts-file

# Uses the same role as the OS plabook but is controlled by the sapos tier setting
  - block:
      - include_role:
          name:     roles-os/1.4-packages
    tags:
      - 1.4-packages

  - block:
      - include_role:
          name: roles-os/1.5-disk-setup
    tags:
      - 1.5-disk-setup


  - block:
    - include_role:
        name:     roles-sap-os/2.6-sap-mounts
    tags:
      - 2.6-sap-mounts


# - role: sap-users                                             # --> roles-sap/sap-users (playbook_02_os_sap_specific_config)
  - block:
    - include_role:
        name:     roles-sap-os/2.5-sap-users                          # TODO: Centiq copy (rework done)
    tags:
      - 2.5-sap-users


# - role: 2.10-sap-notes                                        # --> roles-sap/sap-users (playbook_02_os_sap_specific_config)
  - block:
    - include_role:
        name:     roles-sap-os/2.10-sap-notes                     # TODO: 
    tags:
      - 2.10-sap-notes






...
# /*----------------------------------------------------------------------------8
# |                                    END                                      |
# +------------------------------------4--------------------------------------*/
