# /*----------------------------------------------------------------------------8
# |                                                                            |
# |         Playbook for performing SAP specific OS configuration tasks         |
# |                                                                            |
# +------------------------------------4--------------------------------------*/
---

- hosts: localhost
  name: Get SAP Password from KeyVault
  remote_user:    "{{ orchestration_ansible_user }}"
  become:         no
  become_user:    root
  gather_facts:   yes
  vars_files:
    - vars/ansible-input-api.yaml                               # API Input template with defaults
  tasks:
  - ansible.builtin.set_fact:
      tier:  hdb

  - include_role:
      name:     roles-misc/0.1-passwords
      public:   yes      
    tags:
       - 0.1-passwords

  - ansible.builtin.file:
      path: "{{ _workspace_directory }}/.step2"
      state: absent


- hosts:          "{{ sap_sid|upper }}_DB  :
                   {{ sap_sid|upper }}_SCS :
                   {{ sap_sid|upper }}_PAS :
                   {{ sap_sid|upper }}_ERS :
                   {{ sap_sid|upper }}_APP :
                   {{ sap_sid|upper }}_WEB"

  name:           OS - SAP specific configuration
  remote_user:    "{{ orchestration_ansible_user }}"                
  become:         yes
  become_user:    root
  gather_facts:   true
  vars_files:
    - vars/ansible-input-api.yaml                               # API Input template with defaults


  tasks:
# -------------------------------------+---------------------------------------8
#
# Build the list of tasks to be executed in order here. 
#
# -------------------------------------+---------------------------------------8
  - ansible.builtin.set_fact:
      tier:     sapos
      hana_password_master:   "{{ hostvars.localhost.sap_password }}"
    tags:
      - always

  - include_role:
      name:     roles-sap-os/2.4-hosts-file



# Uses the same role as the OS plabook but is controlled by the sapos tier setting

  - block:
      - include_role:
          name:     roles-os/1.11-accounts
    tags:
      - 1.11-accounts


  - block:
      - include_role:
          name:     roles-os/1.4-packages
    tags:
      - 1.4-packages

  - block:
      - include_role:
          name: roles-os/1.5-disk-setup
    tags:
      - 1.5-disk-setup
  
  - block:
      - include_role:
          name: roles-os/1.9-kernelparameters
    tags:
      - 1.9-kernelparameters

  - block:
      - include_role:
          name:     roles-sap-os/2.5-sap-users                          # TODO: Centiq copy (rework done)
    tags:
      - 2.5-sap-users

  - block:
    - include_role:
        name:     roles-sap-os/2.6-sap-mounts
    tags:
      - 2.6-sap-mounts

# - role: 2.10-sap-notes                                        # --> roles-sap/sap-users (playbook_02_os_sap_specific_config)
  - block:
    - include_role:
        name:     roles-sap-os/2.10-sap-notes                     # TODO: 
    tags:
      - 2.10-sap-notes




- hosts: localhost
  name: Log results
  remote_user:    "{{ orchestration_ansible_user }}"
  become:         no
  become_user:    root
  gather_facts:   yes
  vars_files:
    - vars/ansible-input-api.yaml                               # API Input template with defaults
  tasks:
  - ansible.builtin.file:
      path: "{{ _workspace_directory }}/.step2"
      state: touch



...
# /*----------------------------------------------------------------------------8
# |                                    END                                      |
# +------------------------------------4--------------------------------------*/
