#   SAP: Register BOM
#   SAP APP: deploy APP Parameter file install template
#   SAP APP: Install

# TODO: Considerations
#         20G+ swap space
#         Livecache: None, HANA Internal, MaxDB External
#         message server acl
#         certificates
#         secure storage key
#

---
- name:  
  ansible.builtin.set_fact:
    sap_inifile:                  "{{ bom_base_name }}-app-{{ ansible_hostname }}.params"
    sap_inifile_template:         "{{ bom_base_name }}-app-inifile-param.j2"


# Returns bom object
- include_role:
    name:                         roles-sap/3.3.1-bom-utility
    tasks_from:                   bom-register
  vars:
    bom_name:                     "{{ bom_base_name }}"


- include_role:
    name:                         roles-sap/3.3.1-bom-utility
    tasks_from:                   bom-template
  vars:
    sap_cd_package_hdbclient:     /usr/sap/install/CD_HDBCLIENT/SAP_HANA_CLIENT
    sap_cd_package_cd1:           /usr/sap/install/CD_EXPORT
    sap_cd_package_cd2:           
    sap_cd_package_cd3:           
    sap_cd_package_cd4:           
    sap_cd_package_cd5:           
    sap_ciInstanceNumber:         '00'
    app_instance_number:          '00'
    sap_ciDialogWPNumber:         12
    sap_ciBtcWPNumber:            8
    sap_installSAPHostAgent:      "false"
    sap_profile_dir:              /sapmnt/{{ sap_sid|upper }}/profile
    sap_scs_hostname:             "{{ query('inventory_hostnames', '{{ sap_sid|upper }}_SCS') | first }}"
    sap_db_hostname:              "{{ query('inventory_hostnames', '{{ sap_sid|upper }}_DB')  | first }}"
    sap_ciVirtualHostname:        "{{ query('inventory_hostnames', '{{ sap_sid|upper }}_PAS') | first }}"
    sap_appVirtualHostname:       "{{ inventory_hostname }}"
# *====================================4=======================================8
#   SAP APP: Install
# 2230669 - System Provisioning Using a Parameter Input File
#

- name: SAP Application install variables
  debug:
    msg: "{{ sap_inifile }}"
    verbosity: 2

- name: SAP Application install variables
  debug:
    msg: "{{ bom.product_ids.app }}"
    verbosity: 2

- name: SAP Application install
  block:
    - name:               "SAP APP Install"
      ansible.builtin.shell: |
                          set -o errexit
                          export TMPDIR=/usr/sap/install
                          ./sapinst SAPINST_INPUT_PARAMETERS_URL=/usr/sap/install/downloads/{{ sap_inifile }}     \
                                    SAPINST_EXECUTE_PRODUCT_ID={{ bom.product_ids.app }}                          \
                                    SAPINST_SKIP_DIALOGS=true                                                     \
                                    SAPINST_START_GUISERVER=false                                                 \
                                    SAPINST_REMOTE_ACCESS_USER={{ sap_sid | lower}}adm                            \
                                    SAPINST_REMOTE_ACCESS_USER_IS_TRUSTED=true                                    \
                                    SAPINST_SKIP_ERRORSTEP=true                                                   \
                                    SAPINST_CWD=/usr/sap/install/SWPM                                             

                          touch /etc/sap_deployment_automation/sap_deployment_app.txt
      args:
        chdir:            /usr/sap/install/SWPM
        creates:          /etc/sap_deployment_automation/sap_deployment_app.txt
  rescue:
    - name:               "SAP APP Install recover"
      ansible.builtin.shell: |
                          set -o errexit
                          export TMPDIR=/usr/sap/install
                          chmod -R 777 /usr/sap/install/sapinst_instdir/
                          chmod -R 777 /tmp/sapinst_instdir/                                                                 
                          chmod -R 740 /usr/sap/install/sapinst_instdir/S4HANA1909/CORE/HDB/INSTALL/AS/APPS
                          chmod 770 /usr/sap/install/sapinst_instdir/S4HANA1909/CORE/HDB/INSTALL/AS/APPS
                          ./sapinst SAPINST_INPUT_PARAMETERS_URL=/usr/sap/install/downloads/{{ sap_inifile }}     \
                                    SAPINST_EXECUTE_PRODUCT_ID={{ bom.product_ids.app }}                          \
                                    SAPINST_SKIP_DIALOGS=true                                                     \
                                    SAPINST_START_GUISERVER=false                                                 \
                                    SAPINST_REMOTE_ACCESS_USER={{ sap_sid | lower }}adm                           \
                                    SAPINST_REMOTE_ACCESS_USER_IS_TRUSTED=true                                    \
                                    SAPINST_SKIP_ERRORSTEP=true                                                   \
                                    SAPINST_CWD=/usr/sap/install/SWPM                                             
                          touch /etc/sap_deployment_automation/sap_deployment_app.txt
      args:
        chdir:            /usr/sap/install/SWPM
        creates:          /etc/sap_deployment_automation/sap_deployment_app.txt
  # Skip when TRUE (test mode)
  # when: not test_new_bom
# *====================================4=======================================8

...
# /*---------------------------------------------------------------------------8
# |                                   END                                      |
# +------------------------------------4--------------------------------------*/
