# /*---------------------------------------------------------------------------8
# |                                                                            |
# |             SAP: Register BOM                                              |
# |         SAP PAS: deploy PAS Parameter file install template                |
# |         SAP PAS: Install                                                   |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

---
- name:                                "PAS Install: Set BOM facts"
  ansible.builtin.set_fact:
    sap_inifile:                       "{{ bom_base_name }}-pas-{{ ansible_hostname }}.params"
    sap_inifile_template:              "{{ bom_base_name }}-pas-inifile-param.j2"


# Returns bom object
- name:                                "PAS Install: Include 3.3.1-bom-utility role"
  ansible.builtin.include_role:
    name:                              roles-sap/3.3.1-bom-utility
    tasks_from:                        bom-register
  vars:
    bom_name:                          "{{ bom_base_name }}"

- name:                                "SCS Install: Include roles-sap/3.3.1-bom-utility role"
  ansible.builtin.include_role:
    name:                              roles-sap/3.3.1-bom-utility
    tasks_from:                        bom-template
  vars:
    sap_cd_package_hdbclient:          /usr/sap/install/CD_HDBCLIENT/SAP_HANA_CLIENT
    sap_cd_package_cd1:                /usr/sap/install/CD_EXPORT
    sap_cd_package_cd2:
    sap_cd_package_cd3:
    sap_cd_package_cd4:
    sap_cd_package_cd5:
    sap_ciInstanceNumber:              '00'
    app_instance_number:
    sap_ciDialogWPNumber:              12
    sap_ciBtcWPNumber:                 8
    sap_installSAPHostAgent:           "false"
    sap_profile_dir:                   /usr/sap/{{ sap_sid|upper }}/SYS/profile
    sap_scs_hostname:                  "{{ query('inventory_hostnames', '{{ sap_sid|upper }}_SCS') | first }}"
    sap_db_hostname:                   "{{ query('inventory_hostnames', '{{ sap_sid|upper }}_DB')  | first }}"
    sap_ciVirtualHostname:             "{{ query('inventory_hostnames', '{{ sap_sid|upper }}_PAS') | first }}"
    sap_appVirtualHostname:
  tags:
    - skip_ansible_lint

# *====================================4=======================================8
#   SAP PAS: Install
# 2230669 - System Provisioning Using a Parameter Input File
#

- name:                                "PAS Install: Create run flag directory"
  ansible.builtin.file:
    path:                              /etc/sap_deployment_automation
    state:                             directory
    mode:                              0755

- name:                                "PAS Install: reset"
  ansible.builtin.file:
    path:                              /etc/sap_deployment_automation/sap_deployment_pas.txt
    state:                             absent
  when:                                reinstall

- name:                                "PAS install: variables"
  ansible.builtin.debug:
    msg:
      - "{{ sap_inifile }}"
      - "{{ bom.product_ids.pas }}"
    verbosity:                         2

- name:                                "PAS Install"
  ansible.builtin.shell: |
                                       set -o errexit
                                       set -o pipefail
                                       export TMPDIR=/usr/sap/install
                                       ./sapinst SAPINST_INPUT_PARAMETERS_URL=/usr/sap/install/downloads/{{ sap_inifile }}     \
                                                 SAPINST_EXECUTE_PRODUCT_ID={{ bom.product_ids.pas }}                          \
                                                 SAPINST_SKIP_DIALOGS=true                                                     \
                                                 SAPINST_START_GUISERVER=false
                                       touch /etc/sap_deployment_automation/sap_deployment_pas.txt
  args:
    chdir:                             /usr/sap/install/SWPM
    creates:                           /etc/sap_deployment_automation/sap_deployment_pas.txt
  tags:
    - skip_ansible_lint
  # Skip when TRUE (test mode)
  # when: not test_new_bom
# *====================================4=======================================8

...
# /*---------------------------------------------------------------------------8
# |                                   END                                      |
# +------------------------------------4--------------------------------------*/
