# /*----------------------------------------------------------------------------8
# |                                                                            |
# |            Role for ensuring the swap space is configured correctly         |
# |                                                                            |
# +------------------------------------4--------------------------------------*/
---
# -------------------------------------+---------------------------------------8
#
# Task: 1.1     - swap space setup
#
# -------------------------------------+---------------------------------------8

# TODO: 20210127 Review
#       1) This could be written to be more efficient
#       2) waagent config should not run on Baremetal
#          -Update: I have assumed that the tier for Baremetal is going to be named "HLI"

- name: Ensure variables are available
  include_vars:
    file: "../../../vars/sap-disks.yaml"

- include_tasks: configure.yaml
  loop: "{{ sap_swap }}"
  when: (item.tier != "HLI") and (item.tier == "all" or item.tier == tier)

...
