#   SAP: Register BOM
#   SAP DBLOAD: deploy DBLOAD Parameter file install template
#   SAP DBLOAD: Install

---
- name:  
  ansible.builtin.set_fact:
    sap_inifile:                  "{{ bom_base_name }}-dbload-{{ ansible_hostname }}.params"
    sap_inifile_template:         "{{ bom_base_name }}-dbload-inifile-param.j2"


# Returns bom object
- include_role:
    name:                         roles-sap/3.3.1-bom-utility
    tasks_from:                   bom-register
  vars:
    bom_name:                     "{{ bom_base_name }}"


- include_role:
    name:                         roles-sap/3.3.1-bom-utility
    tasks_from:                   bom-template
  vars:

    sap_cd_package_hdbclient:     /usr/sap/install/CD_HDBCLIENT/SAP_HANA_CLIENT
    sap_cd_package_cd1:           /usr/sap/install/CD_EXPORT
    sap_cd_package_cd2:           
    sap_cd_package_cd3:           
    sap_cd_package_cd4:           
    sap_cd_package_cd5:           
    sap_ciInstanceNumber:         
    app_instance_number:          
    sap_ciDialogWPNumber:         
    sap_ciBtcWPNumber:            
    sap_installSAPHostAgent:      
    sap_profile_dir:              /sapmnt/{{ sap_sid|upper }}/profile
    sap_scs_hostname:             "{{ query('inventory_hostnames', '{{ sap_sid|upper }}_SCS') | first }}"
    sap_db_hostname:              "{{ query('inventory_hostnames', '{{ sap_sid|upper }}_DB')  | first }}"
    sap_ciVirtualHostname:        
    sap_appVirtualHostname:       


# *====================================4=======================================8
#   SAP DBLOAD: Install
# 2230669 - System Provisioning Using a Parameter Input File
#
- name:               "SAP DBLOAD Install"
  ansible.builtin.shell: |
                      set -o errexit
                      mkdir -p /etc/sap_deployment_automation
                      export TMPDIR=/usr/sap/install
                      ./sapinst SAPINST_INPUT_PARAMETERS_URL=/usr/sap/install/downloads/{{ sap_inifile }}     \
                                SAPINST_EXECUTE_PRODUCT_ID={{ bom.product_ids.dbl }}                          \
                                SAPINST_SKIP_DIALOGS=true                                                     \
                                SAPINST_START_GUISERVER=false
                      touch /etc/sap_deployment_automation/sap_deployment_dbload.txt
  args:
    chdir:            /usr/sap/install/SWPM
    creates:          /etc/sap_deployment_automation/sap_deployment_dbload.txt
   # Skip when TRUE (test mode)
  # when: not test_new_bom
# *====================================4=======================================8

...
# /*---------------------------------------------------------------------------8
# |                                   END                                      |
# +------------------------------------4--------------------------------------*/
