
- name: Get Deployer Keyvault name from keyvault
  ansible.builtin.command: >-
    az keyvault secret show
      --vault-name {{ kv_uri }}
      --name {{ deployer_kv_name }}
  changed_when: false
  register: deployer_kv_name_secret

- name: Save Deployer Keyvault name
  ansible.builtin.set_fact:
    deployer_kv_name: >-
      {{ (deployer_kv_name_secret.stdout | from_json).value }}


- name: Debug, Deployer Keyvault
  ansible.builtin.debug: 
    var: deployer_kv_name
    verbosity: 2


- name: Extract SAP Binaries Storage Account information
  ansible.builtin.command: >-
    az keyvault secret show
      --vault-name {{ deployer_kv_name }}
      --name {{ sapbits_location_secret }}
  changed_when: false
  register: sapbits_location_base_path_secret
  no_log: false

- name: Save SAP Binaries Storage Account information
  ansible.builtin.set_fact:
    sapbits_location_base_path: >-
      {{ (sapbits_location_base_path_secret.stdout | from_json).value }}

- name: Debug, storage account
  ansible.builtin.debug: 
    var: sapbits_location_base_path
    verbosity: 2
    

- name: Extract SAP Binaries Storage Account SAS
  ansible.builtin.command: >-
    az keyvault secret show
      --vault-name {{ deployer_kv_name }}
      --name {{ sapbits_sas_token_secret }}
  changed_when: false
  register: sapbits_sas_token_secret

- name: Extract SAP Binaries Storage Account SAS
  ansible.builtin.set_fact:
    sapbits_sas_token: >-
      {{ (sapbits_sas_token_secret.stdout | from_json).value }}
  no_log: false

- name: Debug, SAS Token
  ansible.builtin.debug: 
    var: sapbits_sas_token
    verbosity: 2
